pipeline {
    agent any

    environment {
        SSHUSERNAME = "ubuntu"
        SCRIPTPATH = "/home/antino/Desktop/jenkins/project"
        IP = "54.196.121.38"
    }

    stages{
        stage('Build Deploy') {
            steps{
              sshagent (credentials: ['jenkins.pem']) {
                sh "ssh -o StrictHostKeyChecking=no ${SSHUSERNAME}@${IP} 'cd ${SCRIPTPATH} && bash -x docker_shell_script.sh 2>&1'"
                
              }
            }
        }
    }
    
}

